version: '3.8'

services:
  numharvest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: numharvest-app
    restart: unless-stopped
    
    # 环境变量
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    
    # 数据卷挂载
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    
    # 内存和CPU限制
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/tmp/healthcheck') else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"